// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddReduxFolder(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function RemoveReduxFolder(arg1:string):Promise<void>;

export function SelectGtaFolder():Promise<string>;

export function SelectReduxFolder():Promise<string>;

export function SetActiveRedux(arg1:string):Promise<void>;

export function SetGtaPath(arg1:string):Promise<void>;

export function SetRunOnStartup(arg1:boolean):Promise<void>;

export function SetStartWindowBox(arg1:boolean):Promise<void>;

export function ToggleAutoInject(arg1:boolean):Promise<void>;
