// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReduxFolder(arg1) {
  return window['go']['main']['App']['AddReduxFolder'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function RemoveReduxFolder(arg1) {
  return window['go']['main']['App']['RemoveReduxFolder'](arg1);
}

export function SelectGtaFolder() {
  return window['go']['main']['App']['SelectGtaFolder']();
}

export function SelectReduxFolder() {
  return window['go']['main']['App']['SelectReduxFolder']();
}

export function SetActiveRedux(arg1) {
  return window['go']['main']['App']['SetActiveRedux'](arg1);
}

export function SetGtaPath(arg1) {
  return window['go']['main']['App']['SetGtaPath'](arg1);
}

export function SetRunOnStartup(arg1) {
  return window['go']['main']['App']['SetRunOnStartup'](arg1);
}

export function SetStartWindowBox(arg1) {
  return window['go']['main']['App']['SetStartWindowBox'](arg1);
}

export function ToggleAutoInject(arg1) {
  return window['go']['main']['App']['ToggleAutoInject'](arg1);
}
